// GENERATO da ~/progetti/hrv_app/lib/l10n/pdf_strings.dart e monitoring_index_texts.dart
// con scripts/gen-monitoring-strings.js. NON modificare a mano: i testi devono
// restare identici a quelli dell'app (stessi nomi, stesse frasi, stesse
// referenze). Per cambiarli si cambia l'app e si rigenera.

export type Lang = 'it' | 'en' | 'de'
export const MONITORING_LANGS: Lang[] = ['it', 'en', 'de']

/** Stringhe di pagina del report 24h (PdfStrings.monitoring). */
export const MONITORING_STRINGS: Record<Lang, Record<string, string>> = {
  "it": {
    "title": "Report Monitoraggio 24h",
    "module": "Monitoraggio",
    "period": "Periodo",
    "device": "Dispositivo",
    "signal": "Qualità segnale",
    "valid_data": "Dati validi",
    "duration": "Durata",
    "beats": "battiti",
    "timeline": "TIMELINE DELLE 24 ORE",
    "legend_recovery": "Recupero",
    "legend_stress": "Attivazione",
    "legend_activity": "Attività",
    "legend_neutral": "Neutro",
    "legend_invalid": "Non valido",
    "night_na": "Notte non disponibile",
    "kpi_recovery": "Tempo in recupero",
    "kpi_hr_min": "HR minima notte",
    "kpi_hr_dip": "Calo HR notturno",
    "summary": "IN SINTESI",
    "night": "LA NOTTE",
    "night_from_events": "dagli eventi sonno/risveglio",
    "night_detected": "rilevata dalla frequenza cardiaca",
    "night_chart": "RMSSD per ora (barre) e frequenza cardiaca (linea)",
    "hr_mean_night": "HR media notte",
    "recovery_trend": "Andamento del recupero",
    "first_3h": "Prime 3 ore",
    "last_3h": "Ultime 3 ore",
    "trend_up": "il recupero cresce nelle ultime ore",
    "trend_down": "il recupero cala nelle ultime ore",
    "trend_flat": "recupero stabile per tutta la notte",
    "trend_na": "non valutabile",
    "awakenings": "Episodi di attivazione stimati",
    "awakenings_note": "sequenze di almeno 3 minuti con HR sopra la mediana notturna del 15%: stima di attivazione, non conteggio di risvegli",
    "night_scores": "SCORE DELLA NOTTE",
    "morning_scores": "Score del risveglio (primi 10 minuti)",
    "trend24": "ANDAMENTO NELLE 24 ORE",
    "trend_hr": "Frequenza cardiaca (bpm)",
    "trend_rmssd": "RMSSD (ms)",
    "events": "EVENTI E RISPOSTA",
    "no_events": "Nessun evento registrato.",
    "ev_time": "Ora",
    "ev_event": "Evento",
    "ev_before": "Prima",
    "ev_after": "Dopo",
    "ev_late": "Dopo 1-3h",
    "ev_response": "Risposta",
    "ev_note": "Risposta = media dei 60 minuti prima contro i 60 minuti dopo e i 60-180 minuti dopo, su finestre valide e non di attività.",
    "params": "PARAMETRI SULLE TRE SERIE",
    "series_full": "Intera",
    "series_night": "Notte",
    "series_day": "Giorno",
    "method": "NOTE METODOLOGICHE",
    "method_text": "Finestre mobili di 5 minuti a passo di 1 minuto. Correzione degli artefatti applicata all'intera serie prima di ogni calcolo; finestre con copertura sotto l'80% o artefatti oltre il 15% escluse dalle statistiche. La scala degli stati è individuale: attività sopra HR riposo + 35% della riserva, recupero e attivazione come scostamento di ln RMSSD di ±0,5 deviazioni robuste dal riferimento personale della registrazione, con frequenza cardiaca rispettivamente sotto e sopra la mediana. Notte dagli eventi o rilevata come il segmento più lungo a bassa frequenza cardiaca. Nessuna stima delle fasi del sonno.",
    "meta": "Registrazione",
    "rr_total": "RR totali",
    "artifacts": "Artefatti (grezzo)",
    "irregular": "Battiti irregolari (pattern)",
    "gaps": "Buchi (fascia staccata)",
    "algorithm": "Algoritmo",
    "disclaimer": "I dati riportati in questo documento sono indicatori di benessere generale basati sull'analisi della variabilità del battito. Non costituiscono diagnosi medica e non sostituiscono il parere di un professionista sanitario. Un dato da approfondire va portato al proprio medico.",
    "profile": "Profilo",
    "profile_breve": "Breve",
    "profile_giornata": "Giornata",
    "profile_notte": "Notte",
    "profile_giorno_notte": "Giorno e notte",
    "profile_ciclo_completo": "Ciclo completo",
    "signal_good": "buona",
    "signal_fair": "media",
    "signal_poor": "insufficiente",
    "artifacts_pct": "Artefatti",
    "coverage_banner": "Mancano circa il {missing}% dei dati: la fascia è rimasta scollegata per circa {gap}. Gli indici che richiedono continuità sono segnalati come non calcolabili o da leggere con cautela.",
    "timeline_reserve": "TIMELINE E RISERVA",
    "reserve_hint": "La curva sopra la barra è la Riserva: sale nel recupero, scende nell'attivazione.",
    "balance": "Bilancio della giornata",
    "night_quality": "Recupero notturno",
    "night_na_short": "Non calcolabile",
    "kpi_pauses": "Pause di recupero",
    "kpi_return": "Tempo di rientro (mediana)",
    "kpi_peak": "Picco della giornata",
    "indices": "COSA DICE LA REGISTRAZIONE",
    "level_good": "buono",
    "level_average": "nella media",
    "level_improve": "da migliorare",
    "frag_ordinato": "ordinato",
    "frag_intermedio": "intermedio",
    "frag_frammentato": "frammentato",
    "reserve_up": "Ricaricata",
    "reserve_down": "Consumata",
    "reserve_flat": "In pari",
    "reserve_detail": "punto più basso alle {min}, più alto alle {max}",
    "pauses_detail": "{n} pause · {min} min in tutto",
    "pause_one": "1 pausa · {min} min",
    "stretch_detail": "dalle {from} alle {to}",
    "return_detail": "caso più lungo {worst} min · {n} momenti di pressione",
    "unit_min_median": "min (mediana)",
    "unit_bpm_night": "atti/min di notte",
    "unit_bpm_day": "atti/min di giorno",
    "resp_note": "stima dal battito, non una misura diretta",
    "resp_day": "di giorno",
    "resp_night": "di notte",
    "time_to_min_detail": "battito più basso {hr} bpm alle {at}",
    "waves_present": "Presenti",
    "waves_faint": "Poco evidenti",
    "waves_detail": "periodo ~{p} min · {c} cicli",
    "unreliable": "copertura sotto il 60%: da leggere con cautela",
    "hour_map": "MAPPA DELLE ORE",
    "hour_map_note": "Colori relativi a questa registrazione: più caldo = battito più alto o più attivazione; più verde = più recupero. Le ore tratteggiate non hanno dati.",
    "rhythm": "RITMO E COMPLESSITÀ",
    "clock_strength": "Forza del ritmo",
    "clock_min": "Ora del minimo",
    "clock_peak": "Ora del picco",
    "clock_indicative": "stima indicativa (sotto le 24 ore)",
    "clock_na": "Orologio interno: servono almeno 18 ore di registrazione",
    "prsa_curves": "Curve PRSA: verde decelerazione, rosso accelerazione",
    "mse_curve": "Curva MSE (SampEn per scala) e Complexity Index",
    "anchors": "ancoraggi",
    "beats_used": "battiti usati",
    "tracts": "Tratti continui",
    "tracts_detail": "{n} tratti · più lungo {longest} · totale {total}",
    "tract_note": "Tutti i parametri sono calcolati SOLO dentro i tratti continui (nessuna interruzione oltre 3 s) di almeno 5 minuti e riportati come media pesata sulla durata dei tratti. Un trattino significa che nessun tratto era abbastanza lungo.",
    "how": "COME SI CALCOLA",
    "how_intro": "Per ogni indice del report: nome semplice, nome tecnico, metodo, requisito minimo di dati, referenza.",
    "how_name": "Indice",
    "how_tech": "Nome tecnico",
    "how_method": "Metodo",
    "how_req": "Requisito minimo",
    "how_ref": "Referenza",
    "valid_windows": "Finestre valide",
    "resp_activation": "attivazione",
    "resp_neutral": "neutro",
    "resp_recovery": "recupero",
    "resp_insufficient": "dati insufficienti"
  },
  "en": {
    "title": "24h Monitoring Report",
    "module": "Monitoring",
    "period": "Period",
    "device": "Device",
    "signal": "Signal quality",
    "valid_data": "Valid data",
    "duration": "Duration",
    "beats": "beats",
    "timeline": "24-HOUR TIMELINE",
    "legend_recovery": "Recovery",
    "legend_stress": "Activation",
    "legend_activity": "Activity",
    "legend_neutral": "Neutral",
    "legend_invalid": "Invalid",
    "night_na": "Night not available",
    "kpi_recovery": "Time in recovery",
    "kpi_hr_min": "Night minimum HR",
    "kpi_hr_dip": "Night HR dip",
    "summary": "IN SHORT",
    "night": "THE NIGHT",
    "night_from_events": "from sleep/wake events",
    "night_detected": "detected from heart rate",
    "night_chart": "Hourly RMSSD (bars) and heart rate (line)",
    "hr_mean_night": "Night mean HR",
    "recovery_trend": "Recovery trend",
    "first_3h": "First 3 hours",
    "last_3h": "Last 3 hours",
    "trend_up": "recovery rises in the last hours",
    "trend_down": "recovery drops in the last hours",
    "trend_flat": "recovery stable through the night",
    "trend_na": "not assessable",
    "awakenings": "Estimated activation episodes",
    "awakenings_note": "runs of at least 3 minutes with HR above the night median by 15%: an activation estimate, not an awakening count",
    "night_scores": "NIGHT SCORES",
    "morning_scores": "Wake-up scores (first 10 minutes)",
    "trend24": "24-HOUR TREND",
    "trend_hr": "Heart rate (bpm)",
    "trend_rmssd": "RMSSD (ms)",
    "events": "EVENTS AND RESPONSE",
    "no_events": "No events recorded.",
    "ev_time": "Time",
    "ev_event": "Event",
    "ev_before": "Before",
    "ev_after": "After",
    "ev_late": "After 1-3h",
    "ev_response": "Response",
    "ev_note": "Response = mean of the 60 minutes before vs the 60 minutes after and 60-180 minutes after, on valid non-activity windows.",
    "params": "PARAMETERS ON THE THREE SERIES",
    "series_full": "Full",
    "series_night": "Night",
    "series_day": "Day",
    "method": "METHODOLOGICAL NOTES",
    "method_text": "5-minute sliding windows with a 1-minute step. Artefact correction applied to the whole series before any computation; windows with coverage below 80% or artefacts above 15% are excluded from statistics. The state scale is individual: activity above resting HR + 35% of the reserve, recovery and activation as a ln RMSSD deviation of ±0.5 robust SD from the personal reference of the recording, with heart rate respectively below and above the median. Night from events or detected as the longest low-heart-rate segment. No sleep-stage estimation.",
    "meta": "Recording",
    "rr_total": "Total RR",
    "artifacts": "Artefacts (raw)",
    "irregular": "Irregular beats (pattern)",
    "gaps": "Gaps (strap off)",
    "algorithm": "Algorithm",
    "disclaimer": "The data in this document are general wellness indicators based on heart rate variability analysis. They are not a medical diagnosis and do not replace the advice of a healthcare professional. Anything worth investigating should be discussed with your doctor.",
    "profile": "Profile",
    "profile_breve": "Short",
    "profile_giornata": "Daytime",
    "profile_notte": "Night",
    "profile_giorno_notte": "Day and night",
    "profile_ciclo_completo": "Full cycle",
    "signal_good": "good",
    "signal_fair": "medium",
    "signal_poor": "insufficient",
    "artifacts_pct": "Artefacts",
    "coverage_banner": "About {missing}% of the data is missing: the strap was disconnected for about {gap}. Indices that need continuity are flagged as not computable or to be read with caution.",
    "timeline_reserve": "TIMELINE AND RESERVE",
    "reserve_hint": "The curve above the bar is your Reserve: it rises in recovery and drops in activation.",
    "balance": "Balance of the day",
    "night_quality": "Night recovery",
    "night_na_short": "Not computable",
    "kpi_pauses": "Recovery pauses",
    "kpi_return": "Return time (median)",
    "kpi_peak": "Peak of the day",
    "indices": "WHAT THE RECORDING SAYS",
    "level_good": "good",
    "level_average": "average",
    "level_improve": "to improve",
    "frag_ordinato": "ordered",
    "frag_intermedio": "intermediate",
    "frag_frammentato": "fragmented",
    "reserve_up": "Recharged",
    "reserve_down": "Depleted",
    "reserve_flat": "Even",
    "reserve_detail": "lowest point at {min}, highest at {max}",
    "pauses_detail": "{n} pauses · {min} min in total",
    "pause_one": "1 pause · {min} min",
    "stretch_detail": "from {from} to {to}",
    "return_detail": "longest case {worst} min · {n} pressure moments",
    "unit_min_median": "min (median)",
    "unit_bpm_night": "breaths/min at night",
    "unit_bpm_day": "breaths/min by day",
    "resp_note": "estimated from the heartbeat, not a direct measure",
    "resp_day": "by day",
    "resp_night": "at night",
    "time_to_min_detail": "lowest heart rate {hr} bpm at {at}",
    "waves_present": "Present",
    "waves_faint": "Faint",
    "waves_detail": "period ~{p} min · {c} cycles",
    "unreliable": "coverage below 60%: read with caution",
    "hour_map": "HOUR MAP",
    "hour_map_note": "Colours are relative to this recording: warmer = higher heart rate or more activation; greener = more recovery. Hatched hours have no data.",
    "rhythm": "RHYTHM AND COMPLEXITY",
    "clock_strength": "Rhythm strength",
    "clock_min": "Time of the minimum",
    "clock_peak": "Time of the peak",
    "clock_indicative": "indicative estimate (under 24 hours)",
    "clock_na": "Internal clock: at least 18 hours of recording are needed",
    "prsa_curves": "PRSA curves: green deceleration, red acceleration",
    "mse_curve": "MSE curve (SampEn per scale) and Complexity Index",
    "anchors": "anchors",
    "beats_used": "beats used",
    "tracts": "Continuous stretches",
    "tracts_detail": "{n} stretches · longest {longest} · total {total}",
    "tract_note": "All parameters are computed ONLY inside continuous stretches (no interruption over 3 s) of at least 5 minutes and reported as a duration-weighted mean. A dash means no stretch was long enough.",
    "how": "HOW IT IS COMPUTED",
    "how_intro": "For every index in the report: plain name, technical name, method, minimum data requirement, reference.",
    "how_name": "Index",
    "how_tech": "Technical name",
    "how_method": "Method",
    "how_req": "Minimum requirement",
    "how_ref": "Reference",
    "valid_windows": "Valid windows",
    "resp_activation": "activation",
    "resp_neutral": "neutral",
    "resp_recovery": "recovery",
    "resp_insufficient": "insufficient data"
  },
  "de": {
    "title": "24h-Monitoring-Bericht",
    "module": "Monitoring",
    "period": "Zeitraum",
    "device": "Gerät",
    "signal": "Signalqualität",
    "valid_data": "Gültige Daten",
    "duration": "Dauer",
    "beats": "Schläge",
    "timeline": "24-STUNDEN-ZEITLEISTE",
    "legend_recovery": "Erholung",
    "legend_stress": "Aktivierung",
    "legend_activity": "Aktivität",
    "legend_neutral": "Neutral",
    "legend_invalid": "Ungültig",
    "night_na": "Nacht nicht verfügbar",
    "kpi_recovery": "Zeit in Erholung",
    "kpi_hr_min": "Minimale HF nachts",
    "kpi_hr_dip": "Nächtlicher HF-Abfall",
    "summary": "KURZ GESAGT",
    "night": "DIE NACHT",
    "night_from_events": "aus Schlaf-/Aufwach-Ereignissen",
    "night_detected": "aus der Herzfrequenz erkannt",
    "night_chart": "RMSSD pro Stunde (Balken) und Herzfrequenz (Linie)",
    "hr_mean_night": "Mittlere HF nachts",
    "recovery_trend": "Verlauf der Erholung",
    "first_3h": "Erste 3 Stunden",
    "last_3h": "Letzte 3 Stunden",
    "trend_up": "die Erholung steigt in den letzten Stunden",
    "trend_down": "die Erholung sinkt in den letzten Stunden",
    "trend_flat": "Erholung die ganze Nacht stabil",
    "trend_na": "nicht bewertbar",
    "awakenings": "Geschätzte Aktivierungsepisoden",
    "awakenings_note": "Abschnitte von mindestens 3 Minuten mit HF 15% über dem Nachtmedian: Schätzung der Aktivierung, keine Zählung von Aufwachphasen",
    "night_scores": "NACHT-SCORES",
    "morning_scores": "Scores nach dem Aufwachen (erste 10 Minuten)",
    "trend24": "VERLAUF ÜBER 24 STUNDEN",
    "trend_hr": "Herzfrequenz (bpm)",
    "trend_rmssd": "RMSSD (ms)",
    "events": "EREIGNISSE UND REAKTION",
    "no_events": "Keine Ereignisse erfasst.",
    "ev_time": "Zeit",
    "ev_event": "Ereignis",
    "ev_before": "Vorher",
    "ev_after": "Nachher",
    "ev_late": "Nach 1-3h",
    "ev_response": "Reaktion",
    "ev_note": "Reaktion = Mittel der 60 Minuten davor gegenüber den 60 Minuten danach und 60-180 Minuten danach, auf gültigen Fenstern ohne Aktivität.",
    "params": "PARAMETER DER DREI REIHEN",
    "series_full": "Gesamt",
    "series_night": "Nacht",
    "series_day": "Tag",
    "method": "METHODISCHE HINWEISE",
    "method_text": "Gleitende 5-Minuten-Fenster mit 1-Minuten-Schritt. Artefaktkorrektur vor jeder Berechnung auf die gesamte Reihe angewendet; Fenster mit Abdeckung unter 80% oder Artefakten über 15% sind aus den Statistiken ausgeschlossen. Die Zustandsskala ist individuell: Aktivität über Ruhe-HF + 35% der Reserve, Erholung und Aktivierung als Abweichung von ln RMSSD um ±0,5 robuste SD vom persönlichen Referenzwert der Aufzeichnung, mit Herzfrequenz unter bzw. über dem Median. Nacht aus Ereignissen oder als längstes Segment mit niedriger Herzfrequenz erkannt. Keine Schätzung von Schlafphasen.",
    "meta": "Aufzeichnung",
    "rr_total": "RR gesamt",
    "artifacts": "Artefakte (roh)",
    "irregular": "Unregelmäßige Schläge (Muster)",
    "gaps": "Lücken (Gurt abgelegt)",
    "algorithm": "Algorithmus",
    "disclaimer": "Die Daten in diesem Dokument sind allgemeine Wellness-Indikatoren auf Basis der Herzfrequenzvariabilität. Sie stellen keine medizinische Diagnose dar und ersetzen nicht den Rat einer medizinischen Fachkraft. Auffälligkeiten sollten mit dem eigenen Arzt besprochen werden.",
    "profile": "Profil",
    "profile_breve": "Kurz",
    "profile_giornata": "Tag",
    "profile_notte": "Nacht",
    "profile_giorno_notte": "Tag und Nacht",
    "profile_ciclo_completo": "Voller Zyklus",
    "signal_good": "gut",
    "signal_fair": "mittel",
    "signal_poor": "unzureichend",
    "artifacts_pct": "Artefakte",
    "coverage_banner": "Etwa {missing}% der Daten fehlen: der Gurt war rund {gap} getrennt. Indizes, die Kontinuität brauchen, sind als nicht berechenbar oder mit Vorsicht zu lesen markiert.",
    "timeline_reserve": "ZEITLEISTE UND RESERVE",
    "reserve_hint": "Die Kurve über dem Balken ist die Reserve: sie steigt in der Erholung und fällt in der Aktivierung.",
    "balance": "Bilanz des Tages",
    "night_quality": "Nächtliche Erholung",
    "night_na_short": "Nicht berechenbar",
    "kpi_pauses": "Erholungspausen",
    "kpi_return": "Rückkehrzeit (Median)",
    "kpi_peak": "Spitze des Tages",
    "indices": "WAS DIE AUFZEICHNUNG SAGT",
    "level_good": "gut",
    "level_average": "durchschnittlich",
    "level_improve": "zu verbessern",
    "frag_ordinato": "geordnet",
    "frag_intermedio": "mittel",
    "frag_frammentato": "fragmentiert",
    "reserve_up": "Aufgeladen",
    "reserve_down": "Verbraucht",
    "reserve_flat": "Ausgeglichen",
    "reserve_detail": "Tiefpunkt um {min}, Höchstpunkt um {max}",
    "pauses_detail": "{n} Pausen · {min} min insgesamt",
    "pause_one": "1 Pause · {min} min",
    "stretch_detail": "von {from} bis {to}",
    "return_detail": "längster Fall {worst} min · {n} Druckmomente",
    "unit_min_median": "min (Median)",
    "unit_bpm_night": "Atemzüge/min nachts",
    "unit_bpm_day": "Atemzüge/min tagsüber",
    "resp_note": "aus dem Herzschlag geschätzt, keine direkte Messung",
    "resp_day": "tagsüber",
    "resp_night": "nachts",
    "time_to_min_detail": "niedrigste Herzfrequenz {hr} bpm um {at}",
    "waves_present": "Vorhanden",
    "waves_faint": "Schwach ausgeprägt",
    "waves_detail": "Periode ~{p} min · {c} Zyklen",
    "unreliable": "Abdeckung unter 60%: mit Vorsicht lesen",
    "hour_map": "STUNDENKARTE",
    "hour_map_note": "Farben relativ zu dieser Aufzeichnung: wärmer = höhere Herzfrequenz oder mehr Aktivierung; grüner = mehr Erholung. Schraffierte Stunden haben keine Daten.",
    "rhythm": "RHYTHMUS UND KOMPLEXITÄT",
    "clock_strength": "Stärke des Rhythmus",
    "clock_min": "Zeit des Minimums",
    "clock_peak": "Zeit des Maximums",
    "clock_indicative": "Richtwert (unter 24 Stunden)",
    "clock_na": "Innere Uhr: mindestens 18 Stunden Aufzeichnung nötig",
    "prsa_curves": "PRSA-Kurven: grün Verlangsamung, rot Beschleunigung",
    "mse_curve": "MSE-Kurve (SampEn je Skala) und Complexity Index",
    "anchors": "Anker",
    "beats_used": "verwendete Schläge",
    "tracts": "Kontinuierliche Abschnitte",
    "tracts_detail": "{n} Abschnitte · längster {longest} · gesamt {total}",
    "tract_note": "Alle Parameter werden NUR innerhalb kontinuierlicher Abschnitte (keine Unterbrechung über 3 s) von mindestens 5 Minuten berechnet und als dauergewichtetes Mittel angegeben. Ein Strich bedeutet, dass kein Abschnitt lang genug war.",
    "how": "WIE ES BERECHNET WIRD",
    "how_intro": "Für jeden Index des Berichts: einfacher Name, technischer Name, Methode, Mindestanforderung an die Daten, Referenz.",
    "how_name": "Index",
    "how_tech": "Technischer Name",
    "how_method": "Methode",
    "how_req": "Mindestanforderung",
    "how_ref": "Referenz",
    "valid_windows": "Gültige Fenster",
    "resp_activation": "Aktivierung",
    "resp_neutral": "neutral",
    "resp_recovery": "Erholung",
    "resp_insufficient": "unzureichende Daten"
  }
}

export type IndexId = 'balance' | 'reserve' | 'recovery_pauses' | 'longest_stretch' | 'peak' | 'return_time' | 'event_response' | 'night_recovery' | 'hr_dip' | 'time_to_min' | 'rest_waves' | 'internal_clock' | 'dc' | 'ac' | 'fragmentation' | 'respiration' | 'hour_map' | 'mse' | 'dfa_alpha2' | 'ulf_vlf'

export interface IndexText {
  name: string
  phrase: string
  tech: string
  method: string
  req: string
  ref: string
  proOnly: boolean
}

/** Testi dei due livelli di ogni indice. IT = MonitoringIndexTexts (fonte di verità), EN/DE = PdfStrings.indexTexts. */
export const INDEX_TEXTS: Record<Lang, Record<IndexId, IndexText>> = {
  it: {
  "balance": {
    "name": "Bilancio della giornata",
    "phrase": "Quanto tempo il tuo corpo ha passato a recuperare rispetto a quanto è rimasto attivato.",
    "tech": "Stress/recovery balance (stress_recovery_balance)",
    "method": "50 + 50 × (min recupero − min attivazione) / (min recupero + min attivazione) sulle finestre di 5 min classificate con la scala individuale (ln RMSSD ± 0,5 MAD, HR vs mediana).",
    "req": "Almeno una finestra valida.",
    "ref": "Firstbeat Technologies, Stress and recovery analysis method (white paper 2014); Task Force ESC/NASPE 1996.",
    "proOnly": false
  },
  "reserve": {
    "name": "Riserva",
    "phrase": "La tua riserva sale quando recuperi e scende quando ti attivi. Qui vedi dove la giornata l'ha consumata e dove l'ha ricaricata.",
    "tech": "Carico cumulativo di ln RMSSD (reserve)",
    "method": "Somma cumulativa, finestra per finestra, dello scarto di ln RMSSD dal riferimento personale: positivo nelle finestre di recupero, negativo in quelle di attivazione, nullo altrove.",
    "req": "Almeno una finestra valida; curva campionata ogni 5 min.",
    "ref": "Firstbeat \"body resources\"; Plews et al. 2013 (ln RMSSD come marcatore giornaliero).",
    "proOnly": false
  },
  "recovery_pauses": {
    "name": "Pause di recupero",
    "phrase": "Quante volte durante la giornata il tuo corpo è riuscito a staccare davvero, e per quanto.",
    "tech": "Episodi di recupero in veglia (recovery_pauses)",
    "method": "Conteggio e durata totale dei tratti consecutivi in stato recupero fuori dalla notte; un tratto conta come pausa se dura almeno 5 minuti.",
    "req": "Profili con ore di veglia (Giornata, Giorno e notte, Ciclo completo).",
    "ref": "Firstbeat Lifestyle Assessment; Föhr et al. 2015.",
    "proOnly": false
  },
  "longest_stretch": {
    "name": "Tratto senza pause",
    "phrase": "Il periodo più lungo in cui sei rimasto attivato senza nessuna pausa di recupero.",
    "tech": "Intervallo massimo fra pause di recupero (longest_stretch)",
    "method": "Massimo intervallo di veglia fra due pause di recupero consecutive (o fra un bordo della veglia e la pausa più vicina).",
    "req": "Profili con ore di veglia.",
    "ref": "Firstbeat Lifestyle Assessment.",
    "proOnly": false
  },
  "peak": {
    "name": "Picco della giornata",
    "phrase": "Il momento in cui il tuo corpo era più sotto pressione.",
    "tech": "Finestra di minimo ln RMSSD (peak_stress_time)",
    "method": "Finestra valida, fuori dall'attività, con il ln RMSSD più basso della registrazione; l'orario è il centro della finestra.",
    "req": "Almeno una finestra valida non di attività.",
    "ref": "Task Force ESC/NASPE 1996.",
    "proOnly": false
  },
  "return_time": {
    "name": "Tempo di rientro",
    "phrase": "Dopo un momento di pressione, quanto ci mette il tuo corpo a tornare in equilibrio.",
    "tech": "Latenza di rientro dopo attivazione (return_time)",
    "method": "Per ogni tratto di attivazione di almeno 10 minuti, minuti fra la sua fine e la prima finestra neutra o di recupero. Mediana sulla registrazione e caso peggiore con orario.",
    "req": "Almeno un tratto di attivazione di 10 minuti seguito da un rientro osservato.",
    "ref": "Stanley, Peake & Buchheit 2013 (cinetica del recupero parasimpatico).",
    "proOnly": false
  },
  "event_response": {
    "name": "Reazione agli eventi",
    "phrase": "Come ha risposto il tuo corpo a quello che hai segnato: caffè, pranzo, riunione, allenamento.",
    "tech": "Risposta agli eventi (event_response)",
    "method": "Media di HR e ln RMSSD nei 60 min prima contro i 60 min dopo e i 60-180 min dopo; etichetta dal delta di ln RMSSD rispetto a ±0,5 MAD.",
    "req": "Almeno 10 finestre valide prima e dopo l'evento.",
    "ref": "Disegno N-of-1; Task Force ESC/NASPE 1996.",
    "proOnly": false
  },
  "night_recovery": {
    "name": "Recupero notturno",
    "phrase": "Quanto bene la notte ha ricaricato le tue riserve.",
    "tech": "Qualità del recupero notturno (night_recovery_quality)",
    "method": "Score Recupero proprietario sulla serie RR della notte (nei tratti continui), +10 se il recupero cresce e il calo HR di almeno il 10 %, −10 se il calo HR < 5 %, limitato a 0-100.",
    "req": "Notte con almeno 30 finestre valide.",
    "ref": "Task Force ESC/NASPE 1996; Plews et al. 2013.",
    "proOnly": false
  },
  "hr_dip": {
    "name": "Calo notturno",
    "phrase": "Di quanto scende il tuo battito di notte rispetto al giorno. Un buon calo vuol dire che il corpo stacca davvero.",
    "tech": "Nocturnal HR dip (hr_dip_percentage)",
    "method": "(HR media di veglia − HR media notturna) / HR media di veglia × 100, sulle finestre valide non di attività.",
    "req": "Notte più almeno 30 finestre valide di veglia come riferimento diurno.",
    "ref": "Task Force ESC/NASPE 1996; Vaz et al. 2005.",
    "proOnly": false
  },
  "time_to_min": {
    "name": "Tempo di discesa",
    "phrase": "Quanto ci mette il tuo corpo a scalare di marcia dopo che ti sei coricato.",
    "tech": "Tempo alla HR minima notturna (time_to_min_hr)",
    "method": "Minuti dall'inizio della notte alla finestra con HR media minima; curva di discesa come media delle finestre ogni 10 minuti.",
    "req": "Notte rilevata con minimo individuabile.",
    "ref": "Burton et al. 2010 (HR nocturnal dip kinetics).",
    "proOnly": false
  },
  "rest_waves": {
    "name": "Onde del riposo",
    "phrase": "Se durante la notte il tuo riposo mostra le onde regolari che ci aspettiamo, circa ogni ora e mezza.",
    "tech": "Cicli ultradiani della RMSSD notturna (ultradian)",
    "method": "Autocorrelazione della serie RMSSD notturna (passo 1 min, buchi interpolati, detrend con media mobile a 60 min) fra 70 e 120 minuti; presenza se il massimo locale supera 0,20.",
    "req": "Almeno 4 ore di notte con dati validi sopra l'80 %; altrimenti \"non valutabile\", mai \"assenti\".",
    "ref": "Brandenberger et al. 2005; Bonnet & Arand 1997.",
    "proOnly": false
  },
  "internal_clock": {
    "name": "Orologio interno",
    "phrase": "Quanto è marcata la differenza fra il tuo giorno e la tua notte, e a che ora il tuo corpo tocca il punto più basso.",
    "tech": "Cosinor a 24 h su HR e ln RMSSD (cosinor)",
    "method": "Fit ai minimi quadrati di Y(t) = MESOR + Ampiezza · cos(2π(t − acrofase)/24) sulla serie oraria; batifase = acrofase + 12 h; robustezza = varianza spiegata.",
    "req": "Almeno 18 ore di dati validi su giorno e notte; sotto le 24 ore la stima è indicativa.",
    "ref": "Halberg 1967; Cornelissen 2014.",
    "proOnly": false
  },
  "dc": {
    "name": "Prontezza di recupero",
    "phrase": "Quanto velocemente il tuo cuore sa rallentare quando può riposare.",
    "tech": "Deceleration Capacity, PRSA (dc)",
    "method": "Ancoraggi RR[i] > RR[i−1] (entro +5 %), finestre di 2L = 60 battiti allineate e mediate, trasformata di Haar DC = (X(0) + X(1) − X(−1) − X(−2)) / 4 (T = 1, s = 2).",
    "req": "Almeno 2 ore di dati validi, anche non contigui.",
    "ref": "Bauer et al., Lancet 2006; Kantelhardt et al. 2007.",
    "proOnly": false
  },
  "ac": {
    "name": "Prontezza di reazione",
    "phrase": "Quanto velocemente il tuo cuore sa accelerare quando serve.",
    "tech": "Acceleration Capacity, PRSA (ac)",
    "method": "Come la DC, con ancoraggi di accelerazione RR[i] < RR[i−1] (entro −5 %).",
    "req": "Almeno 2 ore di dati validi, anche non contigui.",
    "ref": "Bauer et al., Lancet 2006; Kantelhardt et al. 2007.",
    "proOnly": false
  },
  "fragmentation": {
    "name": "Ordine del battito",
    "phrase": "Se la variabilità del tuo battito è ordinata o disordinata. Tanta variabilità non è sempre un bene: qui vediamo se è ben organizzata.",
    "tech": "Heart Rate Fragmentation: PIP, IALS, PSS, PAS (fragmentation)",
    "method": "Sulle differenze successive degli RR nei tratti continui: % di punti di inflessione, inverso della lunghezza media dei segmenti, % di RR in segmenti < 3, % di RR in segmenti alternanti di almeno 4. Etichetta dal PIP: < 55 ordinato, 55-65 intermedio, > 65 frammentato.",
    "req": "Almeno 1000 battiti in tratti continui.",
    "ref": "Costa, Davis & Goldberger 2017.",
    "proOnly": false
  },
  "respiration": {
    "name": "Respiro stimato",
    "phrase": "Quanti respiri al minuto fai, stimati dal tuo battito. Di notte dovrebbe scendere.",
    "tech": "Frequenza respiratoria derivata dall'HRV (respiration)",
    "method": "Per ogni finestra valida, picco della banda HF (0,15-0,40 Hz) dello spettro degli RR ricampionati a 4 Hz, convertito in atti/min. È una stima derivata dal battito, non una misura diretta del respiro.",
    "req": "Almeno 10 finestre con un picco HF prominente.",
    "ref": "Schäfer & Kratky 2008.",
    "proOnly": false
  },
  "hour_map": {
    "name": "Mappa delle ore",
    "phrase": "Ora per ora, come è andata la tua giornata.",
    "tech": "Pattern orario (hourly_pattern)",
    "method": "Per ogni ora: mediana di HR, ln RMSSD e LF/HF sulle finestre valide e stato prevalente.",
    "req": "Profili con ore di veglia.",
    "ref": "Task Force ESC/NASPE 1996.",
    "proOnly": false
  },
  "mse": {
    "name": "Ricchezza di regolazione",
    "phrase": "Quanto è ricca, su più scale di tempo, la regolazione del battito.",
    "tech": "Multiscale Entropy e Complexity Index (mse)",
    "method": "Sample Entropy (m = 2, r = 0,15 · SD) su serie coarse-grained a scale 1-20; CI = area sotto la curva. Calcolo a scansione ordinata su blocchi di 6000 battiti (max 4, distribuiti), media dei blocchi.",
    "req": "Almeno 10.000 battiti in tratti continui.",
    "ref": "Costa, Goldberger & Peng 2002, 2005.",
    "proOnly": true
  },
  "dfa_alpha2": {
    "name": "Coerenza a lungo termine",
    "phrase": "Quanto il battito conserva una struttura anche su scale lunghe.",
    "tech": "DFA α2, scale 16-64 (dfa_alpha2)",
    "method": "Detrended Fluctuation Analysis sulle scale 16-64 battiti per ogni tratto continuo, media pesata sui battiti.",
    "req": "Almeno 1000 battiti in un tratto continuo.",
    "ref": "Peng et al. 1995; Huikuri et al. 2000.",
    "proOnly": true
  },
  "ulf_vlf": {
    "name": "Bande lente (ULF, VLF)",
    "phrase": "La parte lentissima della variabilità, legata a termoregolazione, ormoni e ritmo giorno/notte.",
    "tech": "Potenze ULF (< 0,003 Hz) e VLF (0,003-0,04 Hz)",
    "method": "Welch (Hann, 50 % di sovrapposizione, segmenti fino a 4096 campioni a 4 Hz) sui tratti continui di almeno 5 minuti; ULF con periodogramma sull'intera serie solo con almeno 24 ore continue.",
    "req": "VLF: tratti di almeno 5 minuti (idealmente 20). ULF: 24 ore continue.",
    "ref": "Task Force ESC/NASPE 1996.",
    "proOnly": true
  }
},
  en: {
  "balance": {
    "name": "Balance of the day",
    "phrase": "How much time your body spent recovering compared with how long it stayed activated.",
    "tech": "Stress/recovery balance",
    "method": "50 + 50 × (recovery min − activation min) / (recovery min + activation min) on 5-min windows classified with the individual scale (ln RMSSD ± 0.5 MAD, HR vs median).",
    "req": "At least one valid window.",
    "ref": "Firstbeat stress and recovery method (2014); Task Force ESC/NASPE 1996.",
    "proOnly": false
  },
  "reserve": {
    "name": "Reserve",
    "phrase": "Your reserve rises when you recover and drops when you activate. Here you see where the day drained it and where it recharged it.",
    "tech": "Cumulative ln RMSSD load",
    "method": "Cumulative sum, window by window, of the ln RMSSD deviation from the personal reference: positive in recovery windows, negative in activation windows, zero elsewhere.",
    "req": "At least one valid window.",
    "ref": "Firstbeat body resources; Plews et al. 2013.",
    "proOnly": false
  },
  "recovery_pauses": {
    "name": "Recovery pauses",
    "phrase": "How many times during the day your body really managed to switch off, and for how long.",
    "tech": "Recovery episodes while awake",
    "method": "Count and total duration of consecutive recovery stretches outside the night; a stretch counts as a pause if it lasts at least 5 minutes.",
    "req": "Profiles with waking hours.",
    "ref": "Firstbeat Lifestyle Assessment; Föhr et al. 2015.",
    "proOnly": false
  },
  "longest_stretch": {
    "name": "Stretch without pauses",
    "phrase": "The longest period in which you stayed activated without any recovery pause.",
    "tech": "Longest interval between recovery pauses",
    "method": "Longest waking interval between two consecutive recovery pauses (or between a waking edge and the nearest pause).",
    "req": "Profiles with waking hours.",
    "ref": "Firstbeat Lifestyle Assessment.",
    "proOnly": false
  },
  "peak": {
    "name": "Peak of the day",
    "phrase": "The moment your body was most under pressure.",
    "tech": "Minimum ln RMSSD window",
    "method": "Valid non-activity window with the lowest ln RMSSD of the recording; the time is the window centre.",
    "req": "At least one valid non-activity window.",
    "ref": "Task Force ESC/NASPE 1996.",
    "proOnly": false
  },
  "return_time": {
    "name": "Return time",
    "phrase": "After a moment of pressure, how long your body takes to get back into balance.",
    "tech": "Return latency after activation",
    "method": "For each activation stretch of at least 10 minutes, minutes between its end and the first neutral or recovery window. Median over the recording and worst case with time.",
    "req": "At least one 10-minute activation stretch followed by an observed return.",
    "ref": "Stanley, Peake & Buchheit 2013.",
    "proOnly": false
  },
  "event_response": {
    "name": "Reaction to events",
    "phrase": "How your body responded to what you marked: coffee, lunch, meeting, training.",
    "tech": "Event response",
    "method": "Mean HR and ln RMSSD 60 min before vs 60 min after and 60-180 min after; label from the ln RMSSD delta against ±0.5 MAD.",
    "req": "At least 10 valid windows before and after the event.",
    "ref": "N-of-1 design; Task Force ESC/NASPE 1996.",
    "proOnly": false
  },
  "night_recovery": {
    "name": "Night recovery",
    "phrase": "How well the night recharged your reserves.",
    "tech": "Night recovery quality",
    "method": "Proprietary Recovery score on the night RR series (continuous stretches), +10 if recovery rises and HR dip of at least 10 %, −10 if HR dip < 5 %, clamped 0-100.",
    "req": "Night with at least 30 valid windows.",
    "ref": "Task Force ESC/NASPE 1996; Plews et al. 2013.",
    "proOnly": false
  },
  "hr_dip": {
    "name": "Night dip",
    "phrase": "How much your heart rate drops at night compared with the day. A good dip means the body really switches off.",
    "tech": "Nocturnal HR dip",
    "method": "(waking mean HR − night mean HR) / waking mean HR × 100 on valid non-activity windows.",
    "req": "Night plus at least 30 valid waking windows as daytime reference.",
    "ref": "Task Force ESC/NASPE 1996; Vaz et al. 2005.",
    "proOnly": false
  },
  "time_to_min": {
    "name": "Descent time",
    "phrase": "How long your body takes to shift down a gear after you go to bed.",
    "tech": "Time to nocturnal minimum HR",
    "method": "Minutes from night start to the window with the lowest mean HR; descent curve as window means every 10 minutes.",
    "req": "Detected night with an identifiable minimum.",
    "ref": "Burton et al. 2010.",
    "proOnly": false
  },
  "rest_waves": {
    "name": "Waves of rest",
    "phrase": "Whether your rest shows the regular waves we expect during the night, about every hour and a half.",
    "tech": "Ultradian cycles of night RMSSD",
    "method": "Autocorrelation of the night RMSSD series (1-min step, gaps interpolated, 60-min moving-average detrend) between 70 and 120 minutes; present if the local maximum exceeds 0.20.",
    "req": "At least 4 hours of night with valid data above 80 %; otherwise \"not assessable\", never \"absent\".",
    "ref": "Brandenberger et al. 2005; Bonnet & Arand 1997.",
    "proOnly": false
  },
  "internal_clock": {
    "name": "Internal clock",
    "phrase": "How marked the difference between your day and your night is, and at what time your body reaches its lowest point.",
    "tech": "24-h cosinor on HR and ln RMSSD",
    "method": "Least-squares fit of Y(t) = MESOR + Amplitude · cos(2π(t − acrophase)/24) on the hourly series; bathyphase = acrophase + 12 h; robustness = explained variance.",
    "req": "At least 18 hours of valid data across day and night; under 24 hours the estimate is indicative.",
    "ref": "Halberg 1967; Cornelissen 2014.",
    "proOnly": false
  },
  "dc": {
    "name": "Recovery readiness",
    "phrase": "How quickly your heart can slow down when it is allowed to rest.",
    "tech": "Deceleration Capacity, PRSA",
    "method": "Anchors RR[i] > RR[i−1] (within +5 %), 2L = 60-beat windows aligned and averaged, Haar transform DC = (X(0) + X(1) − X(−1) − X(−2)) / 4 (T = 1, s = 2).",
    "req": "At least 2 hours of valid data, not necessarily contiguous.",
    "ref": "Bauer et al., Lancet 2006; Kantelhardt et al. 2007.",
    "proOnly": false
  },
  "ac": {
    "name": "Reaction readiness",
    "phrase": "How quickly your heart can speed up when needed.",
    "tech": "Acceleration Capacity, PRSA",
    "method": "As DC, with acceleration anchors RR[i] < RR[i−1] (within −5 %).",
    "req": "At least 2 hours of valid data, not necessarily contiguous.",
    "ref": "Bauer et al., Lancet 2006; Kantelhardt et al. 2007.",
    "proOnly": false
  },
  "fragmentation": {
    "name": "Order of the heartbeat",
    "phrase": "Whether your heartbeat variability is ordered or disordered. A lot of variability is not always good: here we see whether it is well organised.",
    "tech": "Heart Rate Fragmentation: PIP, IALS, PSS, PAS",
    "method": "On successive RR differences within continuous stretches: % inflection points, inverse mean segment length, % RR in segments < 3, % RR in alternating segments of at least 4. Label from PIP: < 55 ordered, 55-65 intermediate, > 65 fragmented.",
    "req": "At least 1000 beats in continuous stretches.",
    "ref": "Costa, Davis & Goldberger 2017.",
    "proOnly": false
  },
  "respiration": {
    "name": "Estimated breathing",
    "phrase": "How many breaths per minute you take, estimated from your heartbeat. At night it should go down.",
    "tech": "HRV-derived respiratory rate",
    "method": "For each valid window, peak of the HF band (0.15-0.40 Hz) of the 4-Hz resampled RR spectrum, converted to breaths/min. An estimate derived from the heartbeat, not a direct measure of breathing.",
    "req": "At least 10 windows with a prominent HF peak.",
    "ref": "Schäfer & Kratky 2008.",
    "proOnly": false
  },
  "hour_map": {
    "name": "Hour map",
    "phrase": "Hour by hour, how your day went.",
    "tech": "Hourly pattern",
    "method": "For each hour: median HR, ln RMSSD and LF/HF on valid windows and prevalent state.",
    "req": "Profiles with waking hours.",
    "ref": "Task Force ESC/NASPE 1996.",
    "proOnly": false
  },
  "mse": {
    "name": "Richness of regulation",
    "phrase": "How rich, across several time scales, the regulation of the heartbeat is.",
    "tech": "Multiscale Entropy and Complexity Index",
    "method": "Sample Entropy (m = 2, r = 0.15 · SD) on coarse-grained series at scales 1-20; CI = area under the curve. Sorted-sweep computation on 6000-beat blocks (max 4, spread), block mean.",
    "req": "At least 10,000 beats in continuous stretches.",
    "ref": "Costa, Goldberger & Peng 2002, 2005.",
    "proOnly": true
  },
  "dfa_alpha2": {
    "name": "Long-term coherence",
    "phrase": "How much the heartbeat keeps a structure even on long scales.",
    "tech": "DFA α2, scales 16-64",
    "method": "Detrended Fluctuation Analysis on scales 16-64 beats for each continuous stretch, beat-weighted mean.",
    "req": "At least 1000 beats in one continuous stretch.",
    "ref": "Peng et al. 1995; Huikuri et al. 2000.",
    "proOnly": true
  },
  "ulf_vlf": {
    "name": "Slow bands (ULF, VLF)",
    "phrase": "The very slow part of variability, linked to thermoregulation, hormones and the day/night rhythm.",
    "tech": "ULF (< 0.003 Hz) and VLF (0.003-0.04 Hz) power",
    "method": "Welch (Hann, 50 % overlap, segments up to 4096 samples at 4 Hz) on continuous stretches of at least 5 minutes; ULF from a whole-series periodogram only with at least 24 continuous hours.",
    "req": "VLF: stretches of at least 5 minutes (ideally 20). ULF: 24 continuous hours.",
    "ref": "Task Force ESC/NASPE 1996.",
    "proOnly": true
  }
},
  de: {
  "balance": {
    "name": "Bilanz des Tages",
    "phrase": "Wie viel Zeit dein Körper mit Erholung verbracht hat, verglichen mit der Zeit in Aktivierung.",
    "tech": "Stress/Erholungs-Bilanz",
    "method": "50 + 50 × (Erholungsmin − Aktivierungsmin) / (Erholungsmin + Aktivierungsmin) auf 5-min-Fenstern, klassifiziert mit der individuellen Skala (ln RMSSD ± 0,5 MAD, HF vs. Median).",
    "req": "Mindestens ein gültiges Fenster.",
    "ref": "Firstbeat Stress-/Erholungsmethode (2014); Task Force ESC/NASPE 1996.",
    "proOnly": false
  },
  "reserve": {
    "name": "Reserve",
    "phrase": "Deine Reserve steigt, wenn du dich erholst, und sinkt, wenn du dich aktivierst. Hier siehst du, wo der Tag sie verbraucht und wo er sie aufgeladen hat.",
    "tech": "Kumulative ln-RMSSD-Last",
    "method": "Kumulative Summe, Fenster für Fenster, der Abweichung von ln RMSSD vom persönlichen Referenzwert: positiv in Erholungsfenstern, negativ in Aktivierungsfenstern, sonst null.",
    "req": "Mindestens ein gültiges Fenster.",
    "ref": "Firstbeat body resources; Plews et al. 2013.",
    "proOnly": false
  },
  "recovery_pauses": {
    "name": "Erholungspausen",
    "phrase": "Wie oft dein Körper tagsüber wirklich abschalten konnte, und wie lange.",
    "tech": "Erholungsepisoden im Wachzustand",
    "method": "Anzahl und Gesamtdauer zusammenhängender Erholungsabschnitte außerhalb der Nacht; ein Abschnitt zählt als Pause ab 5 Minuten.",
    "req": "Profile mit Wachstunden.",
    "ref": "Firstbeat Lifestyle Assessment; Föhr et al. 2015.",
    "proOnly": false
  },
  "longest_stretch": {
    "name": "Abschnitt ohne Pausen",
    "phrase": "Die längste Zeit, in der du aktiviert geblieben bist, ohne eine einzige Erholungspause.",
    "tech": "Längstes Intervall zwischen Erholungspausen",
    "method": "Längstes Wachintervall zwischen zwei aufeinanderfolgenden Erholungspausen (oder zwischen einem Rand der Wachzeit und der nächsten Pause).",
    "req": "Profile mit Wachstunden.",
    "ref": "Firstbeat Lifestyle Assessment.",
    "proOnly": false
  },
  "peak": {
    "name": "Spitze des Tages",
    "phrase": "Der Moment, in dem dein Körper am stärksten unter Druck stand.",
    "tech": "Fenster mit minimalem ln RMSSD",
    "method": "Gültiges Fenster ohne Aktivität mit dem niedrigsten ln RMSSD der Aufzeichnung; die Zeit ist die Fenstermitte.",
    "req": "Mindestens ein gültiges Fenster ohne Aktivität.",
    "ref": "Task Force ESC/NASPE 1996.",
    "proOnly": false
  },
  "return_time": {
    "name": "Rückkehrzeit",
    "phrase": "Wie lange dein Körper nach einem Druckmoment braucht, um ins Gleichgewicht zurückzukehren.",
    "tech": "Rückkehrlatenz nach Aktivierung",
    "method": "Für jeden Aktivierungsabschnitt von mindestens 10 Minuten: Minuten zwischen seinem Ende und dem ersten neutralen oder Erholungsfenster. Median über die Aufzeichnung und schlechtester Fall mit Uhrzeit.",
    "req": "Mindestens ein 10-minütiger Aktivierungsabschnitt mit beobachteter Rückkehr.",
    "ref": "Stanley, Peake & Buchheit 2013.",
    "proOnly": false
  },
  "event_response": {
    "name": "Reaktion auf Ereignisse",
    "phrase": "Wie dein Körper auf das reagiert hat, was du markiert hast: Kaffee, Mittagessen, Besprechung, Training.",
    "tech": "Ereignisreaktion",
    "method": "Mittel von HF und ln RMSSD 60 min davor gegenüber 60 min danach und 60-180 min danach; Etikett aus der ln-RMSSD-Differenz gegen ±0,5 MAD.",
    "req": "Mindestens 10 gültige Fenster vor und nach dem Ereignis.",
    "ref": "N-of-1-Design; Task Force ESC/NASPE 1996.",
    "proOnly": false
  },
  "night_recovery": {
    "name": "Nächtliche Erholung",
    "phrase": "Wie gut die Nacht deine Reserven aufgeladen hat.",
    "tech": "Qualität der nächtlichen Erholung",
    "method": "Proprietärer Erholungs-Score auf der nächtlichen RR-Reihe (kontinuierliche Abschnitte), +10 wenn die Erholung steigt und der HF-Abfall von mindestens 10 %, −10 wenn der HF-Abfall < 5 %, begrenzt auf 0-100.",
    "req": "Nacht mit mindestens 30 gültigen Fenstern.",
    "ref": "Task Force ESC/NASPE 1996; Plews et al. 2013.",
    "proOnly": false
  },
  "hr_dip": {
    "name": "Nächtlicher Abfall",
    "phrase": "Wie stark dein Puls nachts gegenüber dem Tag sinkt. Ein guter Abfall bedeutet, dass der Körper wirklich abschaltet.",
    "tech": "Nächtlicher HF-Abfall",
    "method": "(mittlere HF wach − mittlere HF nachts) / mittlere HF wach × 100 auf gültigen Fenstern ohne Aktivität.",
    "req": "Nacht plus mindestens 30 gültige Wachfenster als Tagesreferenz.",
    "ref": "Task Force ESC/NASPE 1996; Vaz et al. 2005.",
    "proOnly": false
  },
  "time_to_min": {
    "name": "Abstiegszeit",
    "phrase": "Wie lange dein Körper braucht, um nach dem Zubettgehen einen Gang herunterzuschalten.",
    "tech": "Zeit bis zur nächtlichen Minimal-HF",
    "method": "Minuten vom Nachtbeginn bis zum Fenster mit der niedrigsten mittleren HF; Abstiegskurve als Fenstermittel alle 10 Minuten.",
    "req": "Erkannte Nacht mit identifizierbarem Minimum.",
    "ref": "Burton et al. 2010.",
    "proOnly": false
  },
  "rest_waves": {
    "name": "Wellen der Ruhe",
    "phrase": "Ob deine Ruhe in der Nacht die regelmäßigen Wellen zeigt, die wir erwarten, etwa alle anderthalb Stunden.",
    "tech": "Ultradiane Zyklen der nächtlichen RMSSD",
    "method": "Autokorrelation der nächtlichen RMSSD-Reihe (1-min-Schritt, Lücken interpoliert, Detrend mit gleitendem 60-min-Mittel) zwischen 70 und 120 Minuten; vorhanden, wenn das lokale Maximum 0,20 übersteigt.",
    "req": "Mindestens 4 Stunden Nacht mit gültigen Daten über 80 %; sonst \"nicht bewertbar\", nie \"fehlend\".",
    "ref": "Brandenberger et al. 2005; Bonnet & Arand 1997.",
    "proOnly": false
  },
  "internal_clock": {
    "name": "Innere Uhr",
    "phrase": "Wie ausgeprägt der Unterschied zwischen deinem Tag und deiner Nacht ist, und um welche Uhrzeit dein Körper seinen Tiefpunkt erreicht.",
    "tech": "24-h-Cosinor auf HF und ln RMSSD",
    "method": "Kleinste-Quadrate-Anpassung von Y(t) = MESOR + Amplitude · cos(2π(t − Akrophase)/24) auf der Stundenreihe; Bathyphase = Akrophase + 12 h; Robustheit = erklärte Varianz.",
    "req": "Mindestens 18 Stunden gültige Daten über Tag und Nacht; unter 24 Stunden ist die Schätzung ein Richtwert.",
    "ref": "Halberg 1967; Cornelissen 2014.",
    "proOnly": false
  },
  "dc": {
    "name": "Erholungsbereitschaft",
    "phrase": "Wie schnell dein Herz langsamer werden kann, wenn es ruhen darf.",
    "tech": "Deceleration Capacity, PRSA",
    "method": "Anker RR[i] > RR[i−1] (innerhalb +5 %), 2L = 60-Schlag-Fenster ausgerichtet und gemittelt, Haar-Transformation DC = (X(0) + X(1) − X(−1) − X(−2)) / 4 (T = 1, s = 2).",
    "req": "Mindestens 2 Stunden gültige Daten, auch nicht zusammenhängend.",
    "ref": "Bauer et al., Lancet 2006; Kantelhardt et al. 2007.",
    "proOnly": false
  },
  "ac": {
    "name": "Reaktionsbereitschaft",
    "phrase": "Wie schnell dein Herz beschleunigen kann, wenn es nötig ist.",
    "tech": "Acceleration Capacity, PRSA",
    "method": "Wie DC, mit Beschleunigungsankern RR[i] < RR[i−1] (innerhalb −5 %).",
    "req": "Mindestens 2 Stunden gültige Daten, auch nicht zusammenhängend.",
    "ref": "Bauer et al., Lancet 2006; Kantelhardt et al. 2007.",
    "proOnly": false
  },
  "fragmentation": {
    "name": "Ordnung des Herzschlags",
    "phrase": "Ob die Variabilität deines Herzschlags geordnet oder ungeordnet ist. Viel Variabilität ist nicht immer gut: hier sehen wir, ob sie gut organisiert ist.",
    "tech": "Heart Rate Fragmentation: PIP, IALS, PSS, PAS",
    "method": "Auf den sukzessiven RR-Differenzen in kontinuierlichen Abschnitten: % Wendepunkte, Kehrwert der mittleren Segmentlänge, % RR in Segmenten < 3, % RR in alternierenden Segmenten von mindestens 4. Etikett aus PIP: < 55 geordnet, 55-65 mittel, > 65 fragmentiert.",
    "req": "Mindestens 1000 Schläge in kontinuierlichen Abschnitten.",
    "ref": "Costa, Davis & Goldberger 2017.",
    "proOnly": false
  },
  "respiration": {
    "name": "Geschätzte Atmung",
    "phrase": "Wie viele Atemzüge pro Minute du machst, geschätzt aus deinem Herzschlag. Nachts sollte sie sinken.",
    "tech": "Aus der HRV abgeleitete Atemfrequenz",
    "method": "Für jedes gültige Fenster: Spitze des HF-Bands (0,15-0,40 Hz) des auf 4 Hz umgetasteten RR-Spektrums, in Atemzüge/min umgerechnet. Eine aus dem Herzschlag abgeleitete Schätzung, keine direkte Messung der Atmung.",
    "req": "Mindestens 10 Fenster mit ausgeprägter HF-Spitze.",
    "ref": "Schäfer & Kratky 2008.",
    "proOnly": false
  },
  "hour_map": {
    "name": "Stundenkarte",
    "phrase": "Stunde für Stunde, wie dein Tag gelaufen ist.",
    "tech": "Stundenmuster",
    "method": "Für jede Stunde: Median von HF, ln RMSSD und LF/HF auf gültigen Fenstern und vorherrschender Zustand.",
    "req": "Profile mit Wachstunden.",
    "ref": "Task Force ESC/NASPE 1996.",
    "proOnly": false
  },
  "mse": {
    "name": "Reichtum der Regulation",
    "phrase": "Wie reich die Regulation des Herzschlags über mehrere Zeitskalen ist.",
    "tech": "Multiscale Entropy und Complexity Index",
    "method": "Sample Entropy (m = 2, r = 0,15 · SD) auf vergröberten Reihen der Skalen 1-20; CI = Fläche unter der Kurve. Berechnung mit sortierter Abtastung auf 6000-Schlag-Blöcken (max. 4, verteilt), Blockmittel.",
    "req": "Mindestens 10.000 Schläge in kontinuierlichen Abschnitten.",
    "ref": "Costa, Goldberger & Peng 2002, 2005.",
    "proOnly": true
  },
  "dfa_alpha2": {
    "name": "Langfristige Kohärenz",
    "phrase": "Wie sehr der Herzschlag auch auf langen Skalen eine Struktur behält.",
    "tech": "DFA α2, Skalen 16-64",
    "method": "Detrended Fluctuation Analysis auf den Skalen 16-64 Schläge für jeden kontinuierlichen Abschnitt, schlaggewichtetes Mittel.",
    "req": "Mindestens 1000 Schläge in einem kontinuierlichen Abschnitt.",
    "ref": "Peng et al. 1995; Huikuri et al. 2000.",
    "proOnly": true
  },
  "ulf_vlf": {
    "name": "Langsame Bänder (ULF, VLF)",
    "phrase": "Der sehr langsame Teil der Variabilität, verbunden mit Thermoregulation, Hormonen und dem Tag/Nacht-Rhythmus.",
    "tech": "Leistung ULF (< 0,003 Hz) und VLF (0,003-0,04 Hz)",
    "method": "Welch (Hann, 50 % Überlappung, Segmente bis 4096 Abtastwerte bei 4 Hz) auf kontinuierlichen Abschnitten von mindestens 5 Minuten; ULF aus einem Periodogramm der gesamten Reihe nur mit mindestens 24 kontinuierlichen Stunden.",
    "req": "VLF: Abschnitte von mindestens 5 Minuten (ideal 20). ULF: 24 kontinuierliche Stunden.",
    "ref": "Task Force ESC/NASPE 1996.",
    "proOnly": true
  }
},
}

/** Nomi dei cinque score proprietari (PdfStrings.strings, chiavi *_score). */
export const SCORE_STRINGS: Record<Lang, Record<string, string>> = {
  "it": {
    "stress_score": "Indice di Stress",
    "recovery_score": "Recupero",
    "balance_score": "Equilibrio",
    "energy_score": "Energia",
    "inflammatory_score": "Adattamento"
  },
  "en": {
    "stress_score": "Stress Index",
    "recovery_score": "Recovery",
    "balance_score": "Balance",
    "energy_score": "Energy",
    "inflammatory_score": "Adaptation"
  },
  "de": {
    "stress_score": "Stressindex",
    "recovery_score": "Erholung",
    "balance_score": "Gleichgewicht",
    "energy_score": "Energie",
    "inflammatory_score": "Anpassung"
  }
}

export function monT(key: string, lang: Lang = 'it'): string {
  return MONITORING_STRINGS[lang]?.[key] ?? MONITORING_STRINGS.it[key] ?? key
}

export function indexText(id: IndexId, lang: Lang = 'it'): IndexText {
  return INDEX_TEXTS[lang]?.[id] ?? INDEX_TEXTS.it[id]
}

export function scoreT(key: string, lang: Lang = 'it'): string {
  return SCORE_STRINGS[lang]?.[key] ?? SCORE_STRINGS.it[key] ?? key
}
