// GENERATO da ~/progetti/hrv_app/lib/l10n/sleep_pdf_strings.dart con
// scripts/gen-monitoring-strings.js. NON modificare a mano: i testi restano
// identici a quelli dell'app.

import type { Lang } from './monitoring-strings'

export const SLEEP_STRINGS: Record<Lang, Record<string, string>> = {
  "it": {
    "title": "Report Sonno",
    "module": "Sonno",
    "night_of": "Notte",
    "duration": "Durata",
    "device": "Dispositivo",
    "serial": "Seriale",
    "signal": "Segnale",
    "signal_good": "ottimo",
    "signal_fair": "discreto",
    "signal_poor": "disturbato",
    "valid_data": "Dati validi",
    "sample_step": "Passo",
    "sleep_score": "Sleep Score",
    "components": "Le quattro componenti",
    "comp_oxygenation": "Ossigenazione",
    "comp_respiratory": "Stabilità respiratoria",
    "comp_cardiac": "Recupero cardiaco",
    "comp_continuity": "Continuità",
    "weights_note": "Pesi: 35 / 30 / 20 / 15 %. Il punteggio del dispositivo non entra nella formula.",
    "weights_note_nomov": "Movimento non disponibile: la continuità non entra nel punteggio, pesi 41 / 35 / 24 %.",
    "summary": "In sintesi",
    "key_numbers": "I numeri chiave",
    "odi3": "ODI3 (cali di almeno 3 punti / ora valida)",
    "odi4": "ODI4 (cali di almeno 4 punti / ora valida)",
    "events": "Eventi di desaturazione",
    "valid_time": "Tempo valido per l'ODI",
    "t90": "Tempo sotto 90 %",
    "t88": "Tempo sotto 88 %",
    "t85": "Tempo sotto 85 %",
    "nadir": "Nadir SpO₂",
    "spo2_mean": "SpO₂ media",
    "spo2_basal": "SpO₂ basale (mediana)",
    "delta_index": "Delta index 12 s",
    "cyclic": "Pattern ciclico",
    "cyclic_none": "nessuna sequenza",
    "cyclic_runs": "sequenze",
    "pr_mean": "Polso medio",
    "pr_min": "Polso minimo",
    "pr_max": "Polso massimo",
    "pr_basal": "Polso basale (10° percentile)",
    "dip": "Calo notturno del polso",
    "trend": "Prime 3 ore › ultime 3 ore",
    "trend_up": "polso in calo nel corso della notte",
    "trend_down": "polso in salita nel corso della notte",
    "trend_flat": "polso stabile",
    "trend_na": "non valutabile",
    "surge_pct": "Eventi con surge di almeno 6 bpm",
    "moved_pct": "Minuti mossi",
    "awakenings": "Risvegli stimati",
    "movement_na": "non disponibile",
    "device_o2score": "O2 score del dispositivo",
    "device_drops4": "Cali di almeno 4 punti contati dal dispositivo",
    "not_analyzable": "Notte non analizzabile",
    "oxygenation": "Ossigenazione",
    "spo2_chart": "SpO₂ media per minuto. Banda rossa: sotto il 90 %. Punti rossi: nadir degli eventi. Tratti vuoti: segnale non valido.",
    "below_threshold": "Tempo sotto soglia (sul tempo valido)",
    "threshold": "Soglia",
    "minutes": "Minuti",
    "percent": "% del tempo valido",
    "band": "Fascia",
    "band_normal": "nella norma",
    "band_observe": "da osservare",
    "band_relevant": "rilevante",
    "odi_normal": "nella norma",
    "odi_mild": "alterazione lieve",
    "odi_moderate": "alterazione moderata",
    "odi_marked": "alterazione marcata",
    "score_poor": "scarso",
    "score_sufficient": "sufficiente",
    "score_good": "buono",
    "score_very_good": "molto buono",
    "score_excellent": "ottimo",
    "probe_off": "Sonda staccata",
    "probe_off_note": "tratto escluso da tutti i calcoli e sottratto dal tempo valido dell'ODI.",
    "heart": "Cuore",
    "pr_chart": "Polso medio per minuto. Linea verde tratteggiata: polso basale. Punti gialli: eventi con surge di almeno 6 bpm.",
    "hourly": "Profilo orario",
    "hour": "Ora",
    "pr": "Polso",
    "events_table": "Eventi di desaturazione (primi 20)",
    "ev_time": "Ora",
    "ev_duration": "Durata",
    "ev_drop": "Calo",
    "ev_nadir": "Nadir",
    "ev_surge": "Surge",
    "no_events": "Nessun calo di almeno 3 punti sotto la baseline locale.",
    "more_events": "altri eventi non elencati",
    "method": "Nota metodologica",
    "method_odi_title": "Come si calcola l'ODI",
    "method_odi": "Un evento di desaturazione inizia quando la SpO₂ scende di almeno 3 punti sotto la baseline locale (mediana dei 120-8 secondi precedenti) e finisce quando risale sopra baseline − 1, o dopo 120 secondi. Gli eventi sotto 10 secondi si scartano, quelli a meno di 10 secondi si fondono. ODI3 e ODI4 sono il numero di eventi con calo di almeno 3 e 4 punti per ora di registrazione valida, cioè al netto dei tratti con sonda staccata. Fasce ODI3: sotto 5 nella norma, 5-14,9 lieve, 15-29,9 moderata, 30 e oltre marcata.",
    "method_t90_title": "Cosa vuol dire il T90",
    "method_t90": "Il T90 è il tempo, in minuti e in percentuale del tempo valido, in cui la SpO₂ è rimasta sotto il 90 %. Sotto l'1 % del tempo è nella norma, fra 1 e 5 % da osservare, oltre il 5 % rilevante. T88 e T85 sono le stesse misure con soglie più basse.",
    "method_score_title": "Sleep Score",
    "method_score": "Quattro componenti da 0 a 100: ossigenazione (SpO₂ media, T90, nadir), stabilità respiratoria (ODI3), recupero cardiaco (calo del polso, trend, surge), continuità (movimento e risvegli stimati). Media pesata 35 / 30 / 20 / 15 %; senza movimento 41 / 35 / 24 %. Il punteggio del dispositivo si riporta come confronto e non entra nella formula.",
    "method_not_title": "Cosa non misura questo esame",
    "method_not": "Non misura le fasi del sonno, il tempo di addormentamento né l'efficienza del sonno: senza EEG non sono difendibili. Il surge del polso e i risvegli stimati dal movimento sono proxy, non conteggi. La frequenza del polso non è la variabilità cardiaca: da questa notte non si calcola l'HRV.",
    "disclaimer_odi": "Questo indice descrive quante volte l'ossigenazione è scesa durante la notte. Non è una diagnosi di apnea del sonno, che richiede un esame specifico. Un valore alterato va portato al proprio medico.",
    "disclaimer": "I dati riportati in questo documento sono indicatori di benessere basati su ossigenazione e frequenza del polso registrate a casa. Non costituiscono diagnosi medica e non sostituiscono il parere di un professionista sanitario.",
    "algorithm": "Algoritmo",
    "page": "Pagina",
    "na": "non disponibile"
  },
  "en": {
    "title": "Sleep Report",
    "module": "Sleep",
    "night_of": "Night",
    "duration": "Duration",
    "device": "Device",
    "serial": "Serial",
    "signal": "Signal",
    "signal_good": "excellent",
    "signal_fair": "fair",
    "signal_poor": "poor",
    "valid_data": "Valid data",
    "sample_step": "Step",
    "sleep_score": "Sleep Score",
    "components": "The four components",
    "comp_oxygenation": "Oxygenation",
    "comp_respiratory": "Respiratory stability",
    "comp_cardiac": "Cardiac recovery",
    "comp_continuity": "Continuity",
    "weights_note": "Weights: 35 / 30 / 20 / 15 %. The device score is not part of the formula.",
    "weights_note_nomov": "Movement not available: continuity is left out, weights 41 / 35 / 24 %.",
    "summary": "In brief",
    "key_numbers": "Key numbers",
    "odi3": "ODI3 (drops of at least 3 points / valid hour)",
    "odi4": "ODI4 (drops of at least 4 points / valid hour)",
    "events": "Desaturation events",
    "valid_time": "Valid time for ODI",
    "t90": "Time below 90 %",
    "t88": "Time below 88 %",
    "t85": "Time below 85 %",
    "nadir": "SpO₂ nadir",
    "spo2_mean": "Mean SpO₂",
    "spo2_basal": "Basal SpO₂ (median)",
    "delta_index": "Delta index 12 s",
    "cyclic": "Cyclic pattern",
    "cyclic_none": "no sequence",
    "cyclic_runs": "sequences",
    "pr_mean": "Mean pulse rate",
    "pr_min": "Minimum pulse rate",
    "pr_max": "Maximum pulse rate",
    "pr_basal": "Basal pulse rate (10th percentile)",
    "dip": "Night-time pulse dip",
    "trend": "First 3 h › last 3 h",
    "trend_up": "pulse rate falling over the night",
    "trend_down": "pulse rate rising over the night",
    "trend_flat": "pulse rate stable",
    "trend_na": "not assessable",
    "surge_pct": "Events with surge of at least 6 bpm",
    "moved_pct": "Restless minutes",
    "awakenings": "Estimated awakenings",
    "movement_na": "not available",
    "device_o2score": "Device O2 score",
    "device_drops4": "Drops of at least 4 points counted by the device",
    "not_analyzable": "Night not analysable",
    "oxygenation": "Oxygenation",
    "spo2_chart": "Mean SpO₂ per minute. Red band: below 90 %. Red dots: event nadirs. Gaps: invalid signal.",
    "below_threshold": "Time below threshold (of valid time)",
    "threshold": "Threshold",
    "minutes": "Minutes",
    "percent": "% of valid time",
    "band": "Band",
    "band_normal": "within range",
    "band_observe": "to watch",
    "band_relevant": "relevant",
    "odi_normal": "within range",
    "odi_mild": "mild alteration",
    "odi_moderate": "moderate alteration",
    "odi_marked": "marked alteration",
    "score_poor": "poor",
    "score_sufficient": "sufficient",
    "score_good": "good",
    "score_very_good": "very good",
    "score_excellent": "excellent",
    "probe_off": "Probe off",
    "probe_off_note": "segment excluded from all calculations and subtracted from the valid ODI time.",
    "heart": "Heart",
    "pr_chart": "Mean pulse rate per minute. Dashed green line: basal pulse rate. Yellow dots: events with surge of at least 6 bpm.",
    "hourly": "Hourly profile",
    "hour": "Hour",
    "pr": "Pulse",
    "events_table": "Desaturation events (first 20)",
    "ev_time": "Time",
    "ev_duration": "Duration",
    "ev_drop": "Drop",
    "ev_nadir": "Nadir",
    "ev_surge": "Surge",
    "no_events": "No drop of at least 3 points below the local baseline.",
    "more_events": "further events not listed",
    "method": "Methodological note",
    "method_odi_title": "How the ODI is calculated",
    "method_odi": "A desaturation event starts when SpO₂ falls at least 3 points below the local baseline (median of the previous 120-8 seconds) and ends when it rises above baseline − 1, or after 120 seconds. Events shorter than 10 seconds are discarded, events less than 10 seconds apart are merged. ODI3 and ODI4 are the number of events with a drop of at least 3 and 4 points per hour of valid recording, i.e. net of probe-off segments. ODI3 bands: below 5 within range, 5-14.9 mild, 15-29.9 moderate, 30 and above marked.",
    "method_t90_title": "What T90 means",
    "method_t90": "T90 is the time, in minutes and as a percentage of valid time, during which SpO₂ stayed below 90 %. Below 1 % of the time is within range, 1 to 5 % to watch, above 5 % relevant. T88 and T85 are the same measures with lower thresholds.",
    "method_score_title": "Sleep Score",
    "method_score": "Four components from 0 to 100: oxygenation (mean SpO₂, T90, nadir), respiratory stability (ODI3), cardiac recovery (pulse dip, trend, surge), continuity (movement and estimated awakenings). Weighted mean 35 / 30 / 20 / 15 %; without movement 41 / 35 / 24 %. The device score is shown for comparison and is not part of the formula.",
    "method_not_title": "What this test does not measure",
    "method_not": "It does not measure sleep stages, sleep latency or sleep efficiency: without EEG they cannot be defended. Pulse surges and movement-based estimated awakenings are proxies, not counts. Pulse rate is not heart rate variability: no HRV is computed from this night.",
    "disclaimer_odi": "This index describes how many times oxygenation dropped during the night. It is not a diagnosis of sleep apnoea, which requires a specific examination. An altered value should be discussed with your doctor.",
    "disclaimer": "The data in this document are wellness indicators based on oxygenation and pulse rate recorded at home. They do not constitute a medical diagnosis and do not replace the advice of a healthcare professional.",
    "algorithm": "Algorithm",
    "page": "Page",
    "na": "not available"
  },
  "de": {
    "title": "Schlafbericht",
    "module": "Schlaf",
    "night_of": "Nacht",
    "duration": "Dauer",
    "device": "Gerät",
    "serial": "Seriennummer",
    "signal": "Signal",
    "signal_good": "sehr gut",
    "signal_fair": "ausreichend",
    "signal_poor": "gestört",
    "valid_data": "Gültige Daten",
    "sample_step": "Schritt",
    "sleep_score": "Sleep Score",
    "components": "Die vier Komponenten",
    "comp_oxygenation": "Sauerstoffsättigung",
    "comp_respiratory": "Atmungsstabilität",
    "comp_cardiac": "Kardiale Erholung",
    "comp_continuity": "Kontinuität",
    "weights_note": "Gewichte: 35 / 30 / 20 / 15 %. Der Gerätewert ist nicht Teil der Formel.",
    "weights_note_nomov": "Bewegung nicht verfügbar: Kontinuität entfällt, Gewichte 41 / 35 / 24 %.",
    "summary": "Kurz gesagt",
    "key_numbers": "Die wichtigsten Zahlen",
    "odi3": "ODI3 (Abfälle von mindestens 3 Punkten / gültige Stunde)",
    "odi4": "ODI4 (Abfälle von mindestens 4 Punkten / gültige Stunde)",
    "events": "Entsättigungsereignisse",
    "valid_time": "Gültige Zeit für den ODI",
    "t90": "Zeit unter 90 %",
    "t88": "Zeit unter 88 %",
    "t85": "Zeit unter 85 %",
    "nadir": "SpO₂-Nadir",
    "spo2_mean": "Mittlere SpO₂",
    "spo2_basal": "Basale SpO₂ (Median)",
    "delta_index": "Delta-Index 12 s",
    "cyclic": "Zyklisches Muster",
    "cyclic_none": "keine Sequenz",
    "cyclic_runs": "Sequenzen",
    "pr_mean": "Mittlerer Puls",
    "pr_min": "Minimaler Puls",
    "pr_max": "Maximaler Puls",
    "pr_basal": "Basaler Puls (10. Perzentil)",
    "dip": "Nächtlicher Pulsabfall",
    "trend": "Erste 3 h › letzte 3 h",
    "trend_up": "Puls sinkt im Verlauf der Nacht",
    "trend_down": "Puls steigt im Verlauf der Nacht",
    "trend_flat": "Puls stabil",
    "trend_na": "nicht beurteilbar",
    "surge_pct": "Ereignisse mit Anstieg von mindestens 6 bpm",
    "moved_pct": "Unruhige Minuten",
    "awakenings": "Geschätzte Aufwachphasen",
    "movement_na": "nicht verfügbar",
    "device_o2score": "O2-Score des Geräts",
    "device_drops4": "Vom Gerät gezählte Abfälle von mindestens 4 Punkten",
    "not_analyzable": "Nacht nicht auswertbar",
    "oxygenation": "Sauerstoffsättigung",
    "spo2_chart": "Mittlere SpO₂ pro Minute. Rotes Band: unter 90 %. Rote Punkte: Nadir der Ereignisse. Lücken: ungültiges Signal.",
    "below_threshold": "Zeit unter Schwelle (der gültigen Zeit)",
    "threshold": "Schwelle",
    "minutes": "Minuten",
    "percent": "% der gültigen Zeit",
    "band": "Bereich",
    "band_normal": "im Normbereich",
    "band_observe": "zu beobachten",
    "band_relevant": "relevant",
    "odi_normal": "im Normbereich",
    "odi_mild": "leichte Veränderung",
    "odi_moderate": "mäßige Veränderung",
    "odi_marked": "ausgeprägte Veränderung",
    "score_poor": "schwach",
    "score_sufficient": "ausreichend",
    "score_good": "gut",
    "score_very_good": "sehr gut",
    "score_excellent": "ausgezeichnet",
    "probe_off": "Sensor gelöst",
    "probe_off_note": "Abschnitt aus allen Berechnungen ausgeschlossen und von der gültigen ODI-Zeit abgezogen.",
    "heart": "Herz",
    "pr_chart": "Mittlerer Puls pro Minute. Grün gestrichelt: basaler Puls. Gelbe Punkte: Ereignisse mit Anstieg von mindestens 6 bpm.",
    "hourly": "Stundenprofil",
    "hour": "Stunde",
    "pr": "Puls",
    "events_table": "Entsättigungsereignisse (erste 20)",
    "ev_time": "Zeit",
    "ev_duration": "Dauer",
    "ev_drop": "Abfall",
    "ev_nadir": "Nadir",
    "ev_surge": "Anstieg",
    "no_events": "Kein Abfall von mindestens 3 Punkten unter die lokale Basislinie.",
    "more_events": "weitere Ereignisse nicht aufgeführt",
    "method": "Methodischer Hinweis",
    "method_odi_title": "So wird der ODI berechnet",
    "method_odi": "Ein Entsättigungsereignis beginnt, wenn die SpO₂ mindestens 3 Punkte unter die lokale Basislinie fällt (Median der vorangehenden 120-8 Sekunden), und endet, wenn sie wieder über Basislinie − 1 steigt oder nach 120 Sekunden. Ereignisse unter 10 Sekunden werden verworfen, Ereignisse mit weniger als 10 Sekunden Abstand zusammengeführt. ODI3 und ODI4 sind die Anzahl der Ereignisse mit einem Abfall von mindestens 3 bzw. 4 Punkten pro Stunde gültiger Aufzeichnung, also ohne die Abschnitte mit gelöstem Sensor. ODI3-Bereiche: unter 5 im Normbereich, 5-14,9 leicht, 15-29,9 mäßig, 30 und mehr ausgeprägt.",
    "method_t90_title": "Was der T90 bedeutet",
    "method_t90": "Der T90 ist die Zeit, in Minuten und in Prozent der gültigen Zeit, in der die SpO₂ unter 90 % lag. Unter 1 % der Zeit ist im Normbereich, 1 bis 5 % zu beobachten, über 5 % relevant. T88 und T85 sind dieselben Maße mit niedrigeren Schwellen.",
    "method_score_title": "Sleep Score",
    "method_score": "Vier Komponenten von 0 bis 100: Sauerstoffsättigung (mittlere SpO₂, T90, Nadir), Atmungsstabilität (ODI3), kardiale Erholung (Pulsabfall, Trend, Anstieg), Kontinuität (Bewegung und geschätzte Aufwachphasen). Gewichteter Mittelwert 35 / 30 / 20 / 15 %; ohne Bewegung 41 / 35 / 24 %. Der Gerätewert dient dem Vergleich und ist nicht Teil der Formel.",
    "method_not_title": "Was diese Untersuchung nicht misst",
    "method_not": "Sie misst weder Schlafphasen noch Einschlafzeit oder Schlafeffizienz: ohne EEG sind sie nicht belastbar. Pulsanstiege und bewegungsbasierte Aufwachphasen sind Näherungen, keine Zählungen. Der Puls ist nicht die Herzratenvariabilität: aus dieser Nacht wird keine HRV berechnet.",
    "disclaimer_odi": "Dieser Index beschreibt, wie oft die Sauerstoffsättigung in der Nacht abgefallen ist. Er ist keine Diagnose einer Schlafapnoe, die eine spezifische Untersuchung erfordert. Ein auffälliger Wert sollte mit dem Arzt besprochen werden.",
    "disclaimer": "Die Daten in diesem Dokument sind Wellness-Indikatoren auf Basis der zu Hause aufgezeichneten Sauerstoffsättigung und des Pulses. Sie stellen keine medizinische Diagnose dar und ersetzen nicht den Rat einer medizinischen Fachkraft.",
    "algorithm": "Algorithmus",
    "page": "Seite",
    "na": "nicht verfügbar"
  }
}

export function sleepT(key: string, lang: Lang = 'it'): string {
  return SLEEP_STRINGS[lang]?.[key] ?? SLEEP_STRINGS.it[key] ?? key
}
